export default function ReportTable({ history, loading, colors }) {
  return (
    <div style={{ background: "white", borderRadius: "15px", boxShadow: "0 4px 10px rgba(0,0,0,0.1)", overflow: "hidden" }}>
      <table style={{ width: "100%", borderCollapse: "collapse" }}>
        <thead style={{ background: colors.green, color: "white" }}>
          <tr>
            <th style={{ padding: "15px" }}>Report ID</th>
            <th>Generated By</th>
            <th>Type</th>
            <th>Date Generated</th>
            <th>Date Range</th>
          </tr>
        </thead>
        <tbody>
          {loading ? <tr><td colSpan="5" style={{padding:"30px", textAlign:"center"}}>Loading...</td></tr> :
            history.map((report) => (
              <tr key={report.ReportID} style={{ borderBottom: "1px solid #eee", textAlign: "center", height: "50px" }}>
                <td>RPT-{String(report.ReportID).padStart(3, '0')}</td>
                <td>{report.Employee?.User?.FirstName} {report.Employee?.User?.LastName}</td>
                <td>{report.ReportType}</td>
                <td>{new Date(report.DateGenerated).toLocaleDateString()}</td>
                <td>{report.DateRangeFrom} to {report.DateRangeTo}</td>
              </tr>
            ))
          }
        </tbody>
      </table>
    </div>
  );
}