export default function ReportTable({ history, loading, colors, onViewReport }) {
  return (
    <div style={{ background: "white", borderRadius: "15px", boxShadow: "0 4px 10px rgba(0,0,0,0.1)", overflow: "hidden" }}>
      <table style={{ width: "100%", borderCollapse: "collapse" }}>
        <thead style={{ background: colors.green, color: "white" }}>
          <tr>
            <th style={{ padding: "15px" }}>Report ID</th>
            <th>Generated By</th>
            <th>Type</th>
            <th>Date Generated</th>
            <th>Time Generated</th>
            <th>Date Range</th>
            <th style={{ padding: "15px" }}>Action</th>
          </tr>
        </thead>
        <tbody>
          {loading ? <tr><td colSpan="7" style={{padding:"30px", textAlign:"center"}}>Loading...</td></tr> :
            history.map((report) => (
              <tr key={report.ReportID} style={{ borderBottom: "1px solid #eee", textAlign: "center", height: "50px" }}>
                <td>RPT-{String(report.ReportID).padStart(3, '0')}</td>
                <td>{report.Employee?.User?.FirstName} {report.Employee?.User?.LastName}</td>
                <td>{report.ReportType}</td>
                <td>{new Date(report.DateGenerated).toLocaleDateString()}</td>
                <td>
                  {report.TimeGenerated ? new Date(`1970-01-01T${report.TimeGenerated}`).toLocaleTimeString('en-US', { 
                    hour: '2-digit', 
                    minute: '2-digit' 
                  }) : '---'}
                </td>
                <td>{report.DateRangeFrom} to {report.DateRangeTo}</td>
                <td>
                  <button 
                    onClick={() => onViewReport(report.ReportID)}
                    style={{ padding: "6px 15px", background: colors.blue, color: "white", border: "none", borderRadius: "5px", cursor: "pointer", fontSize: "12px", fontWeight: "bold" }}
                  >
                    View
                  </button>
                </td>
              </tr>
            ))
          }
        </tbody>
      </table>
    </div>
  );
}